### ISSUE TITLE
Add new card

### ISSUE THREAD

**Issue by olimart** [olimart/kanban#3]
Render card form when click on 'add new card'. Ability to close form which toggle back 'add new card' tag.

**Comment by anishdcruz** [comment]
I am looking into it now, it is tricky, but i know there is some solution to this.

**Comment by kyrsquir** [comment]
07142da

**Comment by olimart** [comment]
It does not work when you create a list first.
Working fine on existing list

Please leave comment on each issue when you want me to review (don't close the issue I will). Also, when you want me to review, just submit pull request. Push your code to GitHub first then click pull request from your repo's page and follow the steps

**Comment by kyrsquir** [comment]
Sorry, it closed automatically after I merged the pull request because of old commit message. I'm not using this type of commit names any more, so it won't happen for future commits.
