### ISSUE TITLE
Bulk create cards

### ISSUE THREAD

**Issue by olimart** [olimart/kanban#4]
Only apply if user creates new card (not on update)

When you enter cardForm input and hit the 'enter' key it should create card. I started added key event but no luck so far 52b9f6acc38158a13f6bf64f564fe8b25184f918

It should also render a new cardForm so user can continue adding a new card (of course hitting the enter key will save and render another cardForm)

let me know if you need further details. Thx.

**Comment by anishdcruz** [comment]
Hi,

I got rid of the card create form, so you can add cards in bulk and fixed the position of cards also.
I think adding 'enter' key press is tricky, since textarea has a default enter action.

Let me know if you need any changes.

**Comment by olimart** [comment]
ok I'll check later.
we can always style input field as texture later, no big deal. Thanks again for your help.

**Comment by olimart** [comment]
Looks like we're not on the same page. Here is the intended behaviour. When I hit 'enter' I can add more cards, we were closer before this commit.
http://quick.as/RaextGqWD
