### ISSUE TITLE
New board

### ISSUE THREAD

**Issue by olimart** [olimart/kanban#7]
See e6b707b00138f1697c1b1c58a8cfe15145f2525e

The idea is to be able to create a new board. When user clicks on the link it should show input field to enter board name. When user clicks on 'cancel' it should toggle back to the original state (link to 'create new board' visible).

That would be a good way to get started with component and understand how everything connects. Especially, since on the create function it will talk to the server. Server functions (CRUD objects) will be available at the root/parent level, meaning that in the create function I will call `@saveBoard()` function. For now it I haven't been able to make component talk to global function such as API-related ones.

on the UI, click on 'Boards' button in the header to view `new-board` component

**Comment by kyrsquir** [comment]
I've made the "Create new board" button to toggle input for new board name which can be toggled back. Which API function should I call to create a new board?

**Comment by olimart** [comment]
POST request to /api/boards
